### ISSUE TITLE
ExpansionError during parsing

### ISSUE THREAD

**Issue by ksteensig** [resin-os/resin-jetson-tx2#88]
I am using v2.17.0+rev1 but I run into an error when building.

```
NOTE: Starting bitbake server...
WARNING: Host distribution "ubuntu-18.04" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Please set a MACHINE in your local.conf or environment


Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Traceback (most recent call last):
  File "../layers/poky/bitbake/bin/bitbake-layers", line 103, in <module>
    ret = main()
  File "../layers/poky/bitbake/bin/bitbake-layers", line 93, in main
    tinfoil.parse_recipes()
  File "../layers/poky/bitbake/lib/bb/tinfoil.py", line 454, in parse_recipes
    self.run_actions(config_params)
  File "../layers/poky/bitbake/lib/bb/tinfoil.py", line 437, in run_actions
    raise TinfoilUIException(ret)
bb.tinfoil.TinfoilUIException: 1
```

To replicate this I clone resin-jetson-tx2, checkout v2.17.0+rev1 and update the submodules.
Then run the following commands from the base directory of the project:

```
./resin-yocto-scripts/build/barys -k -m jetson-tx2 --dry-run
cd build
../layers/poky/bitbake/bin/bitbake-layers show-recipes
```

**Comment by floion** [comment]
Hi. What are the commands you use to clone and build?

**Comment by ksteensig** [comment]
https://github.com/resin-os/resin-jetson-tx2

**Comment by ksteensig** [comment]
```
git clone https://github.com/resin-os/resin-jetson-tx2
cd resin-jetson-tx2
git checkout v2.17.0+rev1
git submodule update --init --recursive
```
But this all seems to be caused by bitbake not supporting Ubuntu 18.04 yet, so I switched back to 16.04 which completely fixed it.

**Comment by ksteensig** [comment]
Although this problem disappears on 16.04, I do have another issue which I haven't encountered on 16.04 before. When running `../layers/poky/bitbake/bin/bitbake tegra-binaries` I get the following error.

```
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    PATH contains '.', './' or '' (empty element), which will break the build, please remove this.
Parsed PATH is ['/home/ksj/Workspace/resin-jetson-tx2/build/tmp/sysroots-uninative/x86_64-linux/usr/bin', '/home/ksj/Workspace/resin-jetson-tx2/layers/poky/scripts', '/home/ksj/Workspace/resin-jetson-tx2/build/tmp/work/aarch64-poky-linux/defaultpkgname/1.0-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux', '/home/ksj/Workspace/resin-jetson-tx2/build/tmp/work/aarch64-poky-linux/defaultpkgname/1.0-r0/recipe-sysroot/usr/bin/crossscripts', '/home/ksj/Workspace/resin-jetson-tx2/build/tmp/work/aarch64-poky-linux/defaultpkgname/1.0-r0/recipe-sysroot-native/usr/sbin', '/home/ksj/Workspace/resin-jetson-tx2/build/tmp/work/aarch64-poky-linux/defaultpkgname/1.0-r0/recipe-sysroot-native/usr/bin', '/home/ksj/Workspace/resin-jetson-tx2/build/tmp/work/aarch64-poky-linux/defaultpkgname/1.0-r0/recipe-sysroot-native/sbin', '/home/ksj/Workspace/resin-jetson-tx2/build/tmp/work/aarch64-poky-linux/defaultpkgname/1.0-r0/recipe-sysroot-native/bin', '', '/home/ksj/Workspace/resin-jetson-tx2/build/tmp/hosttools']
```

A few months ago I ran bitbake directly like this as far as I can remember, and here I could easily build tegra-binaries without any issues. I highly supsect I am doing something wrong here (maybe not including something in my PATH?). But it makes it hard to test new recipes for resin-jetson-tx2.

Regards, Kasper.

**Comment by ksteensig** [comment]
I found out how to run the bitbake environment manually, as it was detailed in the raspberry pi repository I just needed to run `source layers/poky/oe-init-build-env`.
